repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
    - id: yamllint
      args: [-c, .github/linters/.yamllint.yml]

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint
      args: [--config, .github/linters/.hadolint.yaml]

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
    - id: shellcheck
      args: [--config=.github/linters/.shellcheckrc]

- repo: local
  hooks:
    - id: helm-lint
      name: Helm lint
      entry: .github/linters/helm-lint.sh
      language: script
      files: ^helm-charts/
      pass_filenames: false
