{{- range $idx, $values := .Values.templates }}
---
{{- if $values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "base-template.fullname" (dict "root" $ "values" $values) }}
  labels:
    {{- include "base-template.labels" (dict "root" $ "values" $values) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "base-template.fullname" (dict "root" $ "values" $values) }}
  minReplicas: {{ $values.autoscaling.minReplicas }}
  maxReplicas: {{ $values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ $values.autoscaling.metrics.name }}
        target:
          type: Utilization
          averageUtilization: {{ $values.autoscaling.metrics.percentage }}  
   behavior:
    {{- with $values.autoscaling.behavior.scaleUp }}
    scaleUp:
      {{- if .policies }}
      policies:
        {{- range .policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
      {{- end }}
      stabilizationWindowSeconds: {{ .stabilizationWindowSeconds }}
    {{- end }}

    {{- with $values.autoscaling.behavior.scaleDown }}
    scaleDown:
      {{- if .policies }}
      policies:
        {{- range .policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
      {{- end }}
      {{- if .selectPolicy }}
      selectPolicy: {{ .selectPolicy }}
      {{- end }}
      stabilizationWindowSeconds: {{ .stabilizationWindowSeconds }}
    {{- end }}
{{- end }}
{{- end }}