{{- range $idx, $values := .Values.templates }}
---
{{- if $values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-template.fullname" (dict "root" $ "values" $values) }}
  labels:
    {{- include "base-template.labels" (dict "root" $ "values" $values) | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
    {{- if $values.service.ports }}
    {{- range $values.service.ports }}
    - name: {{ .name | default "http" }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: TCP
      {{- if eq $values.service.type "NodePort" }}
      nodePort: {{ .nodePort | default "null" }}
      {{- end }}
    {{- end }}
    {{- else }}
    - name: {{ $values.service.portName | default "http" }}
      port: {{ $values.service.port }}
      targetPort: {{ $values.service.port }}
      protocol: TCP
      {{- if eq $values.service.type "NodePort" }}
      nodePort: {{ $values.service.nodePort | default "null" }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "base-template.selectorLabels" (dict "root" $ "values" $values) | nindent 4 }}
{{- end }}
{{- end }}