
{{- range $idx, $values := .Values.templates }}
---
{{- if $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-template.serviceAccountName" (dict "root" $ "values" $values) }}
  labels:
    {{- include "base-template.labels" (dict "root" $ "values" $values) | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $values.serviceAccount.automount }}
{{- end }}
{{- end }}