{{- if and .Values.browserless.enabled .Values.browserless.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "openclaw-stack.browserlessName" . }}
  labels:
    {{- include "openclaw-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: browserless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "openclaw-stack.browserlessName" . }}
  minReplicas: {{ .Values.browserless.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.browserless.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.browserless.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
