{{- if .Values.browserless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw-stack.browserlessName" . }}
  labels:
    {{- include "openclaw-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: browserless
spec:
  type: {{ .Values.browserless.service.type }}
  ports:
    - port: {{ .Values.browserless.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openclaw-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: browserless
{{- end }}
