########################################################
# Global
########################################################
global:
  imageRegistry: 
  imagePullSecrets: []
  defaultStorageClass: 
  storageClass: 

########################################################
# Redis
########################################################
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1024Mi
    persistence:
      enabled: false

########################################################
# PostgreSQL
########################################################
postgresql:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    username: admin
    password: qwer1234
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 1024Mi
  primary:
    persistence:
      enabled: true
      size: 8Gi
    initdb:
      scripts:
        create-databases.sql: |
          CREATE DATABASE default;


########################################################
# Minio
########################################################
minio:
  enabled: true
  nameOverride: minio
  mode: distributed
  auth:
    rootUser: admin
    rootPassword: qwer1234
  provisioning:
    enabled: true
    sleepTime: 30s
    buckets:
      - name: default
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 2048Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: minio.oss-data-infra.io
  apiIngress:
    enabled: true
    ingressClassName: nginx
    hostname: minio-api.oss-data-infra.io
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  persistence:
    enabled: true
    size: 10Gi
  statefulset:
    replicaCount: 4
    drivesPerNode: 1
