########################################################
# Global
########################################################
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""

########################################################
# Applications
########################################################
apps: {}