apiVersion: v2
name: oss-ai-stack
description: A Helm chart for Kubernetes

type: application

version: 0.1.2

appVersion: "1.0.0"

dependencies:
  - name: template-deployment
    version: 0.3.6
    repository: oci://registry-1.docker.io/cagojeiger
    alias: open-source-services
    condition: open-source-services.enabled