########################################################
# Global
########################################################
global:
  imageRegistry: 
  imagePullSecrets: []
  defaultStorageClass: 
  storageClass: 

########################################################
# Open Source Services
########################################################
open-source-services:
  enabled: true
  templates:
    ########################################################
    # n8n
    # License: Sustainable Use License(SUL), The n8n Enterprise License
    ########################################################
    - name: n8n
      image:
        repository: docker.n8n.io/n8nio/n8n
        pullPolicy: IfNotPresent
        tag: "latest"
      service:
        enabled: true
        port: 5678
        portName: http
      persistence:
        enabled: true
        name: n8n-data-pvc
        size: 10Gi
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data-pvc
      volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      livenessProbe:
        httpGet:
          path: /
          port: http
      readinessProbe:
        httpGet:
          path: /
          port: http
      ingress:
        enabled: true
        className: nginx
        annotations: {}
        hosts:
          - host: n8n.sso-ai-stack.io
            paths:
              - path: /
                pathType: ImplementationSpecific