apiVersion: v2
name: argocd-pj
description: ArgoCD PJ (Project Jelly) - A Helm chart for ArgoCD with automatic secret management
type: application
version: 9.0.17-pj-0.1.0
appVersion: "3.0.5"
keywords:
  - argocd
  - gitops
  - continuous-delivery
home: https://argoproj.github.io/cd/
sources:
  - https://github.com/argoproj/argo-cd
maintainers:
  - name: auto-action
    email: cagojeiger@naver.com

dependencies:
  - name: argo-cd
    version: "9.0.17"
    repository: oci://registry-1.docker.io/bitnamicharts