ignored:
  - DL3008 # PIN versions in apt-get install
  - DL3013 # Use specific versions in pip install
  - DL3018 # Pin versions in apk add
  - DL3059 # Multiple consecutive RUN instructions should be a single one with AND

trustedRegistries:
  - docker.io
  - gcr.io
