extends: default

rules:
  line-length:
    max: 120
    level: warning
  trailing-spaces: enable
  new-lines: 
    type: unix
  comments:
    min-spaces-from-content: 1
  document-start:
    present: true
  document-end:
    present: false
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

ignore: |
  node_modules/
  .git/
  .github/CODEOWNERS
