{{- range $index, $values := .Values.templates }}
---
{{- if and $values.clusterRole $values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
rules:
  {{- toYaml $values.clusterRole.rules | nindent 2 }}
{{- end }}
{{- end }}
