{{- range $idx, $values := .Values.templates }}
---
{{- if and $values.clusterRole $values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "template-deployment.serviceAccountName" (dict "root" $ "values" $values) }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
