{{- range $key, $values := .Values.templates }}
---
{{- if and $values.istioIngress $values.istioIngress.enabled $values.istioIngress.gateway.create }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}-gateway
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
  {{- with $values.istioIngress.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: {{ $values.istioIngress.gateway.istioLabel | default "ingressgateway" }}
  servers:
    {{- if $values.istioIngress.gateway.servers }}
    {{- toYaml $values.istioIngress.gateway.servers | nindent 4 }}
    {{- else }}
    {{- /* Default HTTP server if no protocols specified or HTTP is in the list */}}
    {{- if or (not $values.istioIngress.gateway.protocols) (has "HTTP" $values.istioIngress.gateway.protocols) }}
    - port:
        number: {{ $values.istioIngress.gateway.httpPort | default 80 }}
        name: {{ $values.istioIngress.gateway.httpPortName | default "http" }}
        protocol: HTTP
      hosts:
        {{- range $values.istioIngress.hosts }}
        - {{ .host | quote }}
        {{- end }}
    {{- end }}
    {{- /* HTTPS server if HTTPS is in the protocols list */}}
    {{- if and $values.istioIngress.gateway.protocols (has "HTTPS" $values.istioIngress.gateway.protocols) }}
    - port:
        number: {{ $values.istioIngress.gateway.httpsPort | default 443 }}
        name: {{ $values.istioIngress.gateway.httpsPortName | default "https" }}
        protocol: HTTPS
      hosts:
        {{- range $values.istioIngress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      tls:
        {{- if $values.istioIngress.gateway.tls }}
        {{- toYaml $values.istioIngress.gateway.tls | nindent 8 }}
        {{- else if $values.istioIngress.gateway.autoTLS }}
        mode: {{ $values.istioIngress.gateway.autoTLSMode | default "SIMPLE" }}
        {{- if eq ($values.istioIngress.gateway.autoTLSMode | default "SIMPLE") "PASSTHROUGH" }}
        {{- else if eq ($values.istioIngress.gateway.autoTLSMode | default "SIMPLE") "AUTO_PASSTHROUGH" }}
        {{- else }}
        credentialName: {{ $values.istioIngress.gateway.credentialName | default (printf "%s-cert" (include "template-deployment.fullname" (dict "root" $ "values" $values))) }}
        {{- end }}
        {{- else }}
        mode: SIMPLE
        credentialName: {{ $values.istioIngress.gateway.credentialName | default (printf "%s-cert" (include "template-deployment.fullname" (dict "root" $ "values" $values))) }}
        {{- end }}
    {{- end }}
    {{- /* Generate servers for additional protocols */}}
    {{- range $protocol := $values.istioIngress.gateway.protocols }}
    {{- if and (ne $protocol "HTTP") (ne $protocol "HTTPS") }}
    - port:
        number: {{ index $values.istioIngress.gateway (printf "%sPort" ($protocol | lower)) | default 0 }}
        name: {{ index $values.istioIngress.gateway (printf "%sPortName" ($protocol | lower)) | default ($protocol | lower) }}
        protocol: {{ $protocol }}
      hosts:
        {{- range $values.istioIngress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      {{- if eq $protocol "TLS" }}
      tls:
        {{- if $values.istioIngress.gateway.tlsConfig }}
        {{- toYaml $values.istioIngress.gateway.tlsConfig | nindent 8 }}
        {{- else if $values.istioIngress.gateway.autoTLS }}
        mode: {{ $values.istioIngress.gateway.autoTLSMode | default "SIMPLE" }}
        {{- if eq ($values.istioIngress.gateway.autoTLSMode | default "SIMPLE") "PASSTHROUGH" }}
        {{- else if eq ($values.istioIngress.gateway.autoTLSMode | default "SIMPLE") "AUTO_PASSTHROUGH" }}
        {{- else }}
        credentialName: {{ $values.istioIngress.gateway.credentialName | default (printf "%s-cert" (include "template-deployment.fullname" (dict "root" $ "values" $values))) }}
        {{- end }}
        {{- else }}
        mode: PASSTHROUGH
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
