{{- range $index, $template := .Values.templates }}
{{- $type := $template.type | default "" }}
{{- $mergedValues := include "template-deployment.mergeValues" (dict "root" $ "values" $template "type" $type) | fromYaml }}
{{- $values := $mergedValues }}
---
{{- if and $values.autoscaling $values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}
  minReplicas: {{ $values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $values.autoscaling.maxReplicas }}
  {{- with $values.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}