{{- range $index, $template := .Values.templates }}
{{- $type := $template.type | default "" }}
{{- $mergedValues := include "template-deployment.mergeValues" (dict "root" $ "values" $template "type" $type) | fromYaml }}
{{- $values := $mergedValues }}
---
{{- if and $values.persistence $values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $values.persistence.name | default (printf "%s-pvc" (include "template-deployment.fullname" (dict "root" $ "values" $values))) }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ $values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $values.persistence.size }}
  {{- $storageClass := "" }}
  {{- if $values.persistence.storageClassName }}
    {{- $storageClass = $values.persistence.storageClassName }}
  {{- else if $.Values.global.storageClass }}
    {{- $storageClass = $.Values.global.storageClass }}
  {{- else if $.Values.global.defaultStorageClass }}
    {{- $storageClass = $.Values.global.defaultStorageClass }}
  {{- end }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
{{- end }}
{{- end }}