{{- range $index, $values := .Values.templates }}
---
{{- if and $values.persistence $values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $values.persistence.name }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ $values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $values.persistence.size }}
  {{- $storageClass := "" }}
  {{- if $.Values.global.storageClass }}
    {{- $storageClass = $.Values.global.storageClass }}
  {{- else if $.Values.global.defaultStorageClass }}
    {{- $storageClass = $.Values.global.defaultStorageClass }}
  {{- else if $values.persistence.storageClassName }}
    {{- $storageClass = $values.persistence.storageClassName }}
  {{- end }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
{{- end }}
{{- end }}