{{- range $index, $values := .Values.templates }}
---
{{- if and $values.persistence $values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $values.persistence.name }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ $values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $values.persistence.size }}
  {{- if not (eq (include "template-deployment.skipStorageClass" .) "true") }}
  storageClassName: {{ $.Values.global.storageClass | default ($.Values.global.defaultStorageClass | default $values.persistence.storageClassName) }}
  {{- end }}
{{- end }}
{{- end }}