{{- range $index, $values := .Values.templates }}
---
{{- if and $values.persistence $values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $values.persistence.name }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ $values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $values.persistence.size }}
  {{- if and $.Release (lookup "v1" "PersistentVolumeClaim" ($.Release.Namespace | default "") $values.persistence.name) }}
  # 이미 존재하는 PVC의 경우 storageClassName을 수정하지 않음
  {{- else }}
  storageClassName: {{ $.Values.global.storageClass | default ($.Values.global.defaultStorageClass | default $values.persistence.storageClassName) }}
  {{- end }}
{{- end }}
{{- end }}