{{- range $index, $template := .Values.templates }}
{{- $type := $template.type | default "" }}
{{- $mergedValues := include "template-deployment.mergeValues" (dict "root" $ "values" $template "type" $type) | fromYaml }}
{{- $values := $mergedValues }}
{{- if $values.secrets }}
{{- range $secretIndex, $secret := $values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template-deployment.fullname" (dict "root" $ "values" $values) }}-{{ $secret.name | default (printf "secret-%d" $secretIndex) }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
type: {{ $secret.type | default "Opaque" }}
{{- with $secret.data }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- with $secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}