{{- range $index, $values := .Values.templates }}
---
{{- if and $values.serviceAccount $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template-deployment.serviceAccountName" (dict "root" $ "values" $values) }}
  labels:
    {{- include "template-deployment.labels" (dict "root" $ "values" $values) | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $values.serviceAccount.automount }}
{{- end }}
{{- end }}