{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
{{- if and $app.clusterRole $app.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
  labels:
    {{- include "quick-deploy.labels" (dict "root" $ "name" $name "app" $app) | nindent 4 }}
rules:
  {{- toYaml $app.clusterRole.rules | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
