{{- range $name, $app := .Values.apps }}
---
{{- if and $app.clusterRole $app.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
  labels:
    {{- include "quick-deploy.labels" (dict "root" $ "name" $name "app" $app) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "quick-deploy.serviceAccountName" (dict "root" $ "name" $name "app" $app) }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
