{{- range $name, $app := .Values.apps }}
{{- if or (not (hasKey $app "enabled")) $app.enabled }}
---
{{- if and $app.configMap $app.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $app.configMap.name | default (include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app)) }}
  labels:
    {{- include "quick-deploy.labels" (dict "root" $ "name" $name "app" $app) | nindent 4 }}
data:
  {{- range $key, $value := $app.configMap.data }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}