{{- range $name, $app := .Values.apps }}
---
{{- if and $app.autoscaling $app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
  labels:
    {{- include "quick-deploy.labels" (dict "root" $ "name" $name "app" $app) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
  minReplicas: {{ $app.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $app.autoscaling.maxReplicas }}
  {{- with $app.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $app.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}