{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
{{- if and $app.podDisruptionBudget $app.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
spec:
  minAvailable: {{ $app.podDisruptionBudget.minAvailable | default 1 }}  
  selector:
    matchLabels:
      {{- include "quick-deploy.selectorLabels" (dict "root" $ "name" $name "app" $app) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}