{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
{{- if and $app.serviceAccount $app.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quick-deploy.serviceAccountName" (dict "root" $ "name" $name "app" $app) }}
  labels:
    {{- include "quick-deploy.labels" (dict "root" $ "name" $name "app" $app) | nindent 4 }}
  {{- with $app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $app.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}