{{- range $name, $app := .Values.apps }}
{{- if and $app.istio $app.istio.enabled $app.istio.virtualService }}
{{- $vs := $app.istio.virtualService }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}-vs
  labels:
    {{- include "quick-deploy.labels" (dict "root" $ "name" $name "app" $app) | nindent 4 }}
spec:
  {{- if $vs.rawSpec }}
  {{- toYaml $vs.rawSpec | nindent 2 }}
  {{- else }}
  {{- if $vs.gateways }}
  gateways:
    {{- toYaml $vs.gateways | nindent 4 }}
  {{- end }}
  {{- if $vs.hosts }}
  hosts:
    {{- toYaml $vs.hosts | nindent 4 }}
  {{- end }}
  {{- if $vs.http }}
  http:
    {{- range $vs.http }}
    - {{- toYaml . | nindent 6 }}
      {{- if not .route }}
      route:
        - destination:
            host: {{ include "quick-deploy.fullname" (dict "root" $ "name" $name "app" $app) }}
            {{- if $app.service }}
            port:
              number: {{ $app.service.port | default 80 }}
            {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}