{{- if .Values.clusterAdmin.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "code-server.fullname" . }}-cluster-admin
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}