apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "code-server.fullname" . }}-cluster-role-binding
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "code-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "code-server.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
