# ClusterRoleBinding for code-server ServiceAccount
# Binds the ServiceAccount to the ClusterRole defined above
# Note: Name kept as '-cluster-admin' for backwards compatibility
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "code-server.fullname" . }}-cluster-admin
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "code-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "code-server.fullname" . }}-cluster-admin
  apiGroup: rbac.authorization.k8s.io
