version: "3.9"

services:
  # 1) 런타임 이미지를 미리 pull만 수행하는 더미 서비스
  runtime-image:
    image: docker.all-hands.dev/all-hands-ai/runtime:0.38-nikolaik
    container_name: runtime-image-puller
    pull_policy: always
    entrypoint: ["true"]

  # 2) OpenHands 애플리케이션
  openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.38
    container_name: openhands-app
    pull_policy: always
    environment:
      SANDBOX_RUNTIME_CONTAINER_IMAGE: docker.all-hands.dev/all-hands-ai/runtime:0.38-nikolaik
      LOG_ALL_EVENTS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true
    restart: "no"
    depends_on:
      - runtime-image
