{{- if .Values.litellm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-for-litellm
  labels:
    {{- include "ops-stack.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
