########################################################
# Global
########################################################
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""

########################################################
# App Profiles
########################################################
appProfiles:
  default: {}

########################################################
# Apps
########################################################
apps: []
