########################################################
# Global
########################################################
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""

########################################################
# Template Defaults
########################################################
templateDefaults:
  # Web application defaults
  web:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    service:
      enabled: true
      type: ClusterIP
      port: 80
      portName: http
    ingress:
      enabled: false
      className: "nginx"
      annotations: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
    readinessProbe:
      httpGet:
        path: /healthz
        port: http
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
  
  # Database application defaults
  database:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    service:
      enabled: true
      type: ClusterIP
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - "healthcheck.sh"
      initialDelaySeconds: 30
      periodSeconds: 10
  
  # Utility application defaults
  utility:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

########################################################
# Templates
########################################################
templates: []
