########################################################
# Global
########################################################
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""

########################################################
# Template Defaults
########################################################
templateDefaults:
  default: {}

########################################################
# Templates
########################################################
templates: []
