########################################################
# Global
########################################################
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""

########################################################
# Templates
########################################################
templates: []
