apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes

type: application

version: 0.1.1

appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 70.4.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
  - name: loki
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: promtail
    version: 6.16.6
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled
