apiVersion: v2
name: ops-stack
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 20.13.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: postgresql
    version: 16.6.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: minio
    version: 16.0.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
  - name: harbor
    version: 24.5.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: harbor.enabled
  - name: gitea
    version: 3.2.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: gitea.enabled
  - name: argo-cd
    version: 7.3.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: argo-cd.enabled
