########################################################
# Global
########################################################
global:
  imageRegistry: 
  imagePullSecrets: []
  defaultStorageClass: 
  storageClass: 

########################################################
# Overrideable values
########################################################
fullnameOverride: ""
nameOverride: ""

########################################################
# Redis
########################################################
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1024Mi
    persistence:
      enabled: false

########################################################
# PostgreSQL
########################################################
postgresql:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    username: admin
    password: qwer1234
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 1024Mi
  primary:
    initdb:
      scripts:
        create-databases.sql: |
          CREATE DATABASE gitea;
          CREATE DATABASE harbor_core;
          CREATE DATABASE litellm;

########################################################
# Minio
########################################################
minio:
  enabled: true
  nameOverride: minio
  mode: distributed
  auth:
    rootUser: admin
    rootPassword: qwer1234
  provisioning:
    enabled: true
    sleepTime: 30s
    buckets:
      - name: default
      - name: harbor
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 2048Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: minio.ops-stack.io
  apiIngress:
    enabled: true
    ingressClassName: nginx
    hostname: minio-api.ops-stack.io
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  persistence:
    enabled: true
    size: 10Gi
  statefulset:
    replicaCount: 4
    drivesPerNode: 1

########################################################
# Harbor
########################################################
harbor:
  enabled: false
  exposureType: ingress
  ingress:
    core:
      hostname: harbor.ops-stack.io
      ingressClassName: nginx
  externalURL: https://harbor.ops-stack.svc.cluster.local:443
  adminPassword: qwer1234
  trivy:
    enabled: false
  service:
    type: ClusterIP
  jobservice:
    updateStrategy:
      type: Recreate
  persistence:
    imageChartStorage:
      type: s3
      s3:
        bucket: harbor
        rootdirectory: /
        accesskey: admin
        secretkey: qwer1234
        secure: false
        regionendpoint: http://minio-api.ops-stack.svc.cluster.local:80
  postgresql:
    enabled: false
  externalDatabase:
    host: ops-stack-postgresql.ops-stack.svc.cluster.local
    port: 5432
    user: admin
    password: qwer1234
    sslmode: disable
    coreDatabase: harbor_core
  redis:
    enabled: false
  externalRedis:
    host: ops-stack-redis-master.ops-stack.svc.cluster.local
    port: 6379

########################################################
# Gitea
########################################################
gitea:
  enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: gitea.ops-stack.io
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  service:
    type: ClusterIP
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 1024Mi
  appName: ops-gitea
  rootURL: https://gitea.ops-stack.io:443
  extraEnvVars:
    - name: GITEA__SERVICE__SHOW_REGISTRATION_BUTTON
      value: "false"
  persistence:
    enabled: true
    size: 10Gi
  adminEmail: admin@ops-stack.io
  adminPassword: qwer1234
  adminUsername: admin
  postgresql:
    enabled: false
  externalDatabase:
    host: ops-stack-postgresql.ops-stack.svc.cluster.local
    port: 5432
    user: admin
    password: qwer1234
    database: gitea

########################################################
# Argo CD
########################################################
argo-cd:
  enabled: true
  config:
    secret:
      argocdServerAdminPassword: qwer1234
  server:
    insecure: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.ops-stack.io
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1024Mi
  repoServer:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1024Mi
  controller:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 1024Mi
  redis:
    enabled: false
  externalRedis:
    host: ops-stack-redis-master.ops-stack.svc.cluster.local
    port: 6379

########################################################
# Vault
########################################################
vault:
  enabled: true
  server:
    replicaCount: 1
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: vault.ops-stack.io

########################################################
# Litellm
########################################################
litellm:
  enabled: true
  masterkey: qwer1234
  ingress:
    enabled: true
    className: nginx
    annotations: {}
    hosts:
      - host: litellm.ops-stack.io
        paths:
          - path: /
            pathType: ImplementationSpecific
  db:
    useExisting: true
    endpoint: ops-stack-postgresql.ops-stack.svc.cluster.local
    database: litellm
    url: postgresql://admin:qwer1234@ops-stack-postgresql.ops-stack.svc.cluster.local:5432/litellm
    secret:
      name: ops-stack-postgres-for-litellm
      usernameKey: username
      passwordKey: password
    deployStandalone: false
  envVars:
    REDIS_HOST: ops-stack-redis-master.ops-stack.svc.cluster.local
    REDIS_PORT: "6379"
    REDIS_PASSWORD: ""
