name: Build and Tag code-server Image

on:
  push:
    paths:
      - 'helm-charts/code-server/**'
      - 'container/code-server/**' # Dockerfile 변경 시에도 빌드
    branches:
      - main # 또는 기본 브랜치 이름
  workflow_dispatch:

jobs:
  build_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get app version from Chart.yaml
        id: get_version
        uses: mikefarah/yq@v4
        with:
          cmd: yq e '.appVersion' helm-charts/code-server/Chart.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./container/code-server
          file: ./container/code-server/Dockerfile
          platforms: linux/amd64,linux/arm64 # 멀티 아키텍처 빌드 설정
          build-args: |
            APP_VERSION=${{ steps.get_chart_version.outputs.result }}
          push: true
          tags: |
            cagojeiger/code-server:${{ steps.get_chart_version.outputs.result }}
            cagojeiger/code-server:latest